import type { PageContent } from "./types";
import { surferLeadBlocks } from "./surfer-lead-blocks";

export const plantArticles: PageContent[] = [
  {
    path: "/plant/what-cannabis-is",
    kind: "article",
    silo: "plant",
    h1: "What Cannabis Is",
    title: "What the Cannabis Plant Actually Is",
    description: "Cannabis explained as an annual flowering plant, including its life cycle, harvested flower, reproductive structure, and resin-bearing surfaces.",
    wordTarget: [1100, 1250],
    intro: [
      "Cannabis is an annual flowering plant whose reproductive flower is the part cultivated and harvested for cannabis flower. It completes its main life cycle within a season, moving from germination through vegetative growth and into flowering. The resin-rich floral clusters that develop late in that cycle carry the structure, aroma, cannabinoids, and terpenes recognized in the finished harvest.",
      "Thinking of cannabis first as a plant creates a clear foundation. Roots, stems, fan leaves, branches, flowers, and resin glands each perform a biological role. Genetics supplies an inherited range, while light, water, nutrition, temperature, root space, and time shape how that range appears. Finished flower is therefore a preserved piece of the plant's reproductive stage and a record of the conditions that supported it.",
      "Presidential Cannabis publishes this what-cannabis-is guide as adult 21+ plant literacy: cannabis as a living annual species rather than a product myth alone; how the life cycle, harvested flower, and resin surface connect to The Cannabis Plant Guide, flower structure, indica-sativa-hybrid language, flower quality, and genetics; and how to keep that literacy observational at a licensed counter. No medical claims. The job is a botanical definition that stays checkable beside the jar.",
    ],
    leadBlocks: surferLeadBlocks["/plant/what-cannabis-is"],
    sections: [
      {
        id: "annual-cycle",
        heading: "An Annual Flowering Cycle",
        paragraphs: [
          "A seed begins by opening and sending a root downward while its first shoot rises toward light. The young plant builds a root network, a central stem, branches, and leaves. During vegetative growth, leaves gather light and the plant expands the structure that will later support flower sites. Cultivators guide this phase through a stable environment and a light schedule suited to active growth.",
          "Flowering begins when the plant receives the seasonal or controlled signal that the growth phase has changed. The spacing between new leaves shortens, flower sites form along branches, and those sites develop into clusters. Female flowers build bracts around their reproductive structures, pistils extend outward, and resin glands become increasingly prominent across the bracts and surrounding small leaves.",
          "As an annual, the plant directs its cycle toward reproduction. The flower supports that purpose, and its resin helps protect exposed reproductive surfaces. Cultivation for flower manages pollination so the plant continues building dense, resinous floral material. The completed cycle gives growers a harvest window in which structure, trichome maturity, aroma, and the whole plant align.",
          "Product myths often skip that living sequence. A jar, a menu title, or a broad indica-sativa-hybrid tag can sound like the whole story, yet each still depends on an annual plant that germinated, vegetated, flowered, and was harvested. Reading cannabis as a species first keeps shelf language from replacing biology.",
          "Traditional growth-form labels and modern breeding notes sit on top of this cycle rather than replacing it. Indica, sativa, and hybrid vocabulary describes historical shape and commerce shorthand; genetics explains inheritance and selection. Neither erases the annual plant underneath the finished flower.",
        ],
        contextualLinks: [
          {
            before: "The Presidential Cannabis ",
            href: "/",
            label: "guide",
            after: " carries this botanical starting point into flower quality, genetics, and practical choosing.",
          },
          {
            before: "The wider ",
            href: "/plant",
            label: "cannabis",
            after: " hub follows the plant through anatomy, trichomes, harvest timing, drying, and cure.",
          },
          {
            before: "Place traditional labels beside the plant with ",
            href: "/plant/indica-sativa-hybrid",
            label: "indica, sativa, hybrid",
            after: " when growth-form shorthand needs the annual cycle underneath it.",
          },
          {
            before: "Follow inheritance and selection through ",
            href: "/genetics",
            label: "Genetics",
            after: " when breeding records explain the range the living plant can express.",
          },
        ],
      },
      {
        id: "harvested-flower",
        heading: "What the Harvest Contains",
        paragraphs: [
          "The harvested material is a collection of many small flowers arranged together. A bract holds the reproductive parts, pistils emerge from the bract, and close sugar leaves extend through the cluster. Many individual sites can gather into a larger cola. After harvest, trimming defines the finished shape while preserving the flower and its resin-bearing surfaces.",
          "Fan leaves belong mainly to the plant's energy-making system and are removed from finished flower. Sugar leaves sit much closer to the floral cluster and often carry visible resin. A careful trim creates a clean presentation while respecting the trichomes on the flower's outer surface. The resulting piece still reflects the original architecture: some cultivars form compact, rounded clusters, while others form longer, more open structures.",
          "The flower's value comes from this complete botanical assembly. Aromatic compounds create its nose, cannabinoids develop in the plant's resin, and the arrangement of bracts and leaves gives each piece its texture and shape. A quality assessment begins by recognizing the flower as organized plant tissue rather than a uniform object.",
          "Anatomy makes that assessment concrete. Bracts, pistils, sugar leaves, and cola organization are the same parts that grew on the living plant; finished appearance and density inherit that map after dry and cure. Flower literacy starts here before aroma, moisture, or storage notes refine the read.",
          "At a licensed counter, keep plant questions observational. Ask which harvest or package dates belong to the jar, how this batch's structure compares with the last delivery of the same name, and whether the producer lists parents or a named cut. Pair answers with what you see and smell so adult 21+ literacy stays botanical, not a medical claim.",
        ],
        contextualLinks: [
          {
            before: "Map the parts in ",
            href: "/plant/the-flower-structure",
            label: "flower structure",
            after: " when bracts, pistils, sugar leaves, and colas need named anatomy.",
          },
          {
            before: "Continue into ",
            href: "/flower",
            label: "The Flower",
            after: " for appearance, aroma, density, moisture, and storage after the plant definition is clear.",
          },
          {
            before: "Return to ",
            href: "/plant",
            label: "The Cannabis Plant Guide",
            after: " for the map from annual biology and resin glands through harvest into post-harvest care.",
          },
        ],
      },
      {
        id: "resin-purpose",
        heading: "Why the Plant Produces Resin",
        paragraphs: [
          "Resin glands form most abundantly on the flower and the small leaves immediately around it. Their rounded heads hold aromatic terpenes and the majority of the plant's cannabinoids. On the living plant, these exposed glands contribute a protective layer around reproductive tissues. Their aroma and physical character interact with the surrounding environment while the flower matures.",
          "Trichome development follows the flowering cycle. Tiny gland types appear across surfaces, while larger stalked glands become especially visible on mature flower. A broad reference range places heads around 25 to 160 microns, while published measurements vary by gland type, genotype, and age. Clear heads can develop toward cloudy and amber tones asynchronously, giving cultivators one useful maturity observation when read across the plant.",
          "This resin-bearing surface connects biology to finished quality. Intact trichomes, defined aroma, sound structure, and a balanced cure all carry information from the living flower. Harvest captures the chosen moment, drying and curing stabilize it, and thoughtful storage preserves it. Understanding what cannabis is ultimately means understanding that chain from annual plant to finished flower.",
          "Reading the gland field keeps the plant definition practical. Coverage and head condition describe what this flower built; they do not replace cultivar identity, harvest timing, or the dry-and-cure handoff that follows. Adults 21+ can note frost, nose, and bract packing together, then ask which window and handling the producer used so the jar stays a botanical record rather than a menu shorthand.",
        ],
        contextualLinks: [
          {
            before: "Study the glandular surface in ",
            href: "/plant/trichomes",
            label: "trichomes",
            after: " when stalked heads, coverage, and clear-to-cloudy-to-amber cues need a closer plant map.",
          },
          {
            before: "Place resin chemistry in botanical context with ",
            href: "/plant/cannabinoids-in-the-plant",
            label: "cannabinoids in the plant",
            after: ", where acidic forms and glandular production explain what the living flower carries.",
          },
          {
            before: "Connect maturity reading to ",
            href: "/plant/harvest-timing",
            label: "harvest timing",
            after: " when the chosen cut decides which resin stage becomes finished flower.",
          },
          {
            before: "Follow the post-harvest handoff in ",
            href: "/plant/drying-and-curing",
            label: "drying and curing",
            after: " once the annual plant's resin surface needs moisture control and stable storage.",
          },
        ],
      },
    ],
    externalLink: { href: "https://presidentialmoonrocks.com/find-us", label: "Find licensed stores with current Presidential selections" },
  },
  {
    path: "/plant/indica-sativa-hybrid",
    kind: "article",
    silo: "plant",
    h1: "Indica Sativa Hybrid Explained",
    title: "Indica Sativa Hybrid Explained: Understanding Cannabis Strain Types",
    description: "The origins and modern value of indica, sativa, and hybrid as traditional descriptors of cannabis structure, geography, and lineage.",
    wordTarget: [1100, 1250],
    intro: [
      "Indica, sativa, and hybrid are traditional cannabis descriptors rooted in plant classification, geography, growth form, and modern commerce. They offer broad historical shorthand rather than a reliable stand-alone measure of ancestry or a current batch. Many commercial cultivars show extensive admixture from repeated hybridization, so breeder records, batch details, aromatic profile, and direct observation provide the clearest picture of the flower in front of you.",
      "The terms remain useful when they are read at the right scale. They can introduce a plant's breeding background, the shape associated with historical populations, and the way a breeder frames a family. They become richer beside parentage, phenotype, cultivation, harvest date, terpene information, cure, and aroma-details that describe the present flower rather than a category alone.",
      "Presidential Cannabis publishes this guide as adult 21+ plant literacy: how the labels entered common language, why growth-form and geography shaped them, and how hybrid breeding now fills most licensed shelves. Shelf tags are introductions, not medical promises or fixed personal-effect guarantees. Product catalogs and retailer paths stay on the official storefronts; this page stays with botanical history, morphology language, lineage reading, and batch evidence.",
    ],
    leadBlocks: surferLeadBlocks["/plant/indica-sativa-hybrid"],
    sections: [
      {
        id: "historical-language",
        heading: "Where the Terms Come From",
        paragraphs: [
          "Cannabis classification developed across botany, agriculture, trade, and regional growing traditions. Plants associated with different regions displayed recognizable patterns because generations of reproduction occurred under local day length, temperature, elevation, season, and human selection. Tall plants with longer spacing and narrower leaflets became associated with one side of the traditional vocabulary, while shorter, broader, more compact plants became associated with another.",
          "Those descriptions began as observations of populations and plant form. They spoke to growth habit, flowering time, leaf shape, branching, and geographic history. Cultivators could use them to anticipate the space a plant might occupy or the season it might prefer. The labels therefore entered common language with a real botanical foundation, even as the plant's movement and continued breeding made family trees more complex.",
          "The word hybrid describes a cross between distinct parents or populations. Cannabis breeding has used crossing extensively, bringing traits from many family lines into modern cultivars. A hybrid may lean toward one historical growth pattern, combine several, or express a fresh balance selected for a particular cultivation environment and flower goal.",
          "As seed and cuttings moved across regions, the tidy map of local populations became harder to hold. Breeders crossed plants that once lived continents apart, and commercial gardens selected for flower density, flowering time, aroma, and canopy fit more than for purity of an old geographic type. The historical words stayed familiar in the market even as the plants behind them became more mixed.",
          "Growth-shape language still has agricultural value. Tall, stretchy plants and compact, broad-leaf plants remain real morphological tendencies that matter for trellis, light, and flowering schedules. Confusion arrives when those same words are treated as promises about personal experience. Shelf tags that say indica or sativa are not medical classifications, and they do not certify how any adult will feel. They are traditional plant descriptors that sit beside lineage and batch detail rather than replacing them.",
        ],
        contextualLinks: [
          {
            before: "Start with the annual plant frame in ",
            href: "/plant/what-cannabis-is",
            label: "what cannabis is",
            after: " when you want the life cycle behind these traditional labels.",
          },
          {
            before: "Compare regional origins and modern crossing in ",
            href: "/genetics/landrace-and-modern",
            label: "landrace and modern genetics",
            after: ", where adaptation history meets today's hybrid reality.",
          },
          {
            before: "Follow family records through ",
            href: "/genetics/lineage",
            label: "lineage",
            after: " when parent names need to sit beside the broad I/S/H tag.",
          },
        ],
      },
      {
        id: "modern-meaning",
        heading: "What the Labels Tell You Today",
        paragraphs: [
          "Today, indica, sativa, and hybrid work best as shorthand for lineage and broad plant tendencies. A breeder or producer may use them to place a cultivar within a familiar family. The terms can also hint at growth pattern, such as internodal spacing, stretch during flowering, flower density, or the length of the flowering cycle. These are starting points that gain precision when parentage and phenotype are known.",
          "Modern flower carries many layers beyond the category. Two plants within a hybrid family can express different phenotypes. The same clone can develop differently across gardens. Harvest timing can capture distinct stages of trichome maturity, and drying and curing can preserve different amounts of aromatic character. By the time flower reaches a package, its current batch contains information that the broad label was never designed to hold by itself.",
          "This is why the labels work as an introduction rather than a stand-alone ancestry or chemistry test. The flower's present aroma, terpene blend, structure, freshness, moisture, and cure give direct evidence. A menu that includes documented parentage, dates, and a terpene panel adds further context. The category opens the conversation, while breeder records and the batch complete it.",
          "Walk a licensed menu today and hybrids fill most of the board. Pure expressions of a single historical population are uncommon in commercial flower; repeated crossing is the ordinary breeding path. That is why two jars tagged hybrid can still differ sharply in aroma, structure, and parentage. The shared word means both come from mixed families, not that they share one chemistry profile or one personal outcome.",
          "Reading parents, cut, and batch separately from the I/S/H tag keeps the conversation concrete. Ask which parents or family the producer lists, whether this is a specific cut, and what harvest and package dates accompany the jar. Those answers sit next to the broad label instead of disappearing into it. At the counter, questions about aroma, structure, and dates turn a three-word category into a plant you can evaluate.",
        ],
        contextualLinks: [
          {
            before: "See how crosses are built in ",
            href: "/genetics/how-strains-are-made",
            label: "how strains are made",
            after: " when hybrid labels need a breeding backstory.",
          },
          {
            before: "Separate genetics from this run in ",
            href: "/genetics/why-two-batches-differ",
            label: "why two batches differ",
            after: ", where garden and post-harvest change explain jar-to-jar range.",
          },
          {
            before: "Bring useful questions to the counter with ",
            href: "/choosing/what-to-ask",
            label: "what to ask",
            after: " so parentage, dates, and aroma stay in view beside the shelf tag.",
          },
          {
            before: "Practice menu literacy in ",
            href: "/choosing/reading-a-menu",
            label: "reading a menu",
            after: " when category columns need supporting batch detail.",
          },
        ],
      },
    ],
    externalLink: { href: "https://presidentialmoonrocks.com/find-us", label: "Explore current Presidential cultivar families nearby" },
  },
  {
    path: "/plant/trichomes",
    kind: "article",
    silo: "plant",
    h1: "Trichomes on the Cannabis Plant",
    title: "Trichomes on the Cannabis Plant",
    description: "Trichomes on living cannabis flower: their location, gland forms, size, maturation, color, protective role, cannabinoids, and terpenes.",
    wordTarget: [1100, 1250],
    intro: [
      "Trichomes are resin glands that grow across cannabis flowers and the small leaves surrounding them. Their heads hold most of the living plant's cannabinoids and terpenes, making them central to aroma, surface character, and harvest observation. On mature flower they create the familiar frosted appearance, while magnification reveals distinct gland shapes and stages of development.",
      "The word trichome covers several hair-like and glandular structures found on plants. Cannabis develops non-glandular hairs as well as resin-producing glands. For flower quality, the glandular types receive the closest attention because their resin connects the living surface to the aromatic and cannabinoid profile preserved after harvest.",
      "Presidential Cannabis publishes this trichomes guide as adult 21+ plant literacy: what glandular resin surfaces are on the living flower, how glandular and non-glandular structures differ in plain language, and how coverage and color talk stay descriptive rather than medical. The brand name here is the company and publisher. Product art and retailer paths stay on the official catalog; this page stays with anatomy, resin appearance, harvest observation, and careful post-harvest handling.",
    ],
    leadBlocks: surferLeadBlocks["/plant/trichomes"],
    sections: [
      {
        id: "location-and-form",
        heading: "Where Trichomes Grow",
        paragraphs: [
          "Trichomes appear most densely on bracts, the small structures that surround the flower's reproductive parts, and on nearby sugar leaves. They can also occur on other above-ground plant surfaces at lower density. Their placement creates a resinous field around the flower, with the greatest visible concentration building as flowering advances.",
          "Bulbous glands are tiny and sit close to the surface. Capitate-sessile glands have a rounded head on a very short base. Capitate-stalked glands rise on a visible stalk and carry a larger rounded head. These stalked glands become the most visually prominent form on mature cannabis flower, especially under magnification.",
          "A broad reference range places trichome heads roughly 25 to 160 microns across, while published measurements vary with gland type, genotype, and age. One study measured bulbous heads at 15 to 30 microns and capitate heads at 40 to 110 microns in its selected plants. Their distribution varies across the flower, so a useful observation looks across several sites rather than concentrating on one patch.",
          "Glandular and non-glandular trichomes share a hair-like presence, yet they do different work. Non-glandular hairs can shade tissue, discourage contact, or alter the microclimate around tender flower parts. Glandular forms build the rounded resin heads that carry aromatic compounds and cannabinoids. When growers and buyers talk about frost, they usually mean those glandular heads across bracts and sugar leaves rather than every hair on the plant.",
          "Coverage also varies by cut, canopy position, and garden conditions. The same clone can present a denser frosted field in one room and a lighter field in another when light, nutrition, humidity, and plant health differ. Batch notes therefore matter beside the cultivar name: strain identity describes genetics, while appearance notes describe what this run actually built on the living surface.",
        ],
        contextualLinks: [
          {
            before: "Return to ",
            href: "/plant",
            label: "The Cannabis Plant Guide",
            after: " for the map from annual biology and resin glands through harvest into post-harvest care.",
          },
          {
            before: "Review the gland-bearing surfaces in ",
            href: "/plant/the-flower-structure",
            label: "the flower structure",
            after: ", where bracts, sugar leaves, and clustered sites explain where frost concentrates.",
          },
          {
            before: "Revisit ",
            href: "/plant/what-cannabis-is",
            label: "what cannabis is",
            after: " when you want the annual cycle and resin purpose behind these microscopic glands.",
          },
        ],
      },
      {
        id: "resin-and-role",
        heading: "What the Glands Hold",
        paragraphs: [
          "The rounded gland head contains resin rich in cannabinoids and terpenes. Cannabinoids begin in acidic form in the living plant. Terpenes supply aromatic notes that can read as earthy, citrus, pepper, pine, floral, fruit, or a more complex blend. Every cultivar carries a mixture, and its proportions can shift with genetics, environment, harvest timing, and handling.",
          "On the plant, this resinous surface contributes to protection around delicate flower tissues. The aromatic and physical qualities of the glands interact with insects, environmental exposure, and the microclimate around the flower. Their biological role belongs to the living reproductive structure, which is also why the plant concentrates so much of its chemical character there.",
          "Trichome abundance is one visible part of flower quality. Condition supplies another. Intact, well-developed heads carry more information than frost alone, and aroma, flower structure, maturity, and cure round out the assessment. The complete surface reflects both what the plant produced and how carefully it was carried through harvest.",
          "Aroma and resin appearance travel together because terpenes sit in the same glandular resin that creates the frosted look. A bright citrus or pine note does not come from sparkle alone, and a heavily frosted surface does not guarantee one aromatic profile. Observation stays concrete when it pairs the visual field with the nose, dates, and structure rather than treating frost as a ranking or a medical promise.",
          "At a licensed counter, trichome talk is useful when it stays observational. Ask how the producer describes coverage and handling for this batch, whether dates sit separate from the strain title, and how the dry and cure were paced to protect the surface. That habit separates cultivar naming from batch appearance and keeps clear, cloudy, and amber language in its agricultural role.",
        ],
        contextualLinks: [
          {
            before: "Connect resin to scent in ",
            href: "/flower/aroma",
            label: "flower aroma",
            after: ", where terpene character explains what the nose reads beside the frosted field.",
          },
          {
            before: "Locate production chemistry in ",
            href: "/plant/cannabinoids-in-the-plant",
            label: "cannabinoids in the living plant",
            after: ", which places acidic forms inside the same gland heads that create visible resin.",
          },
          {
            before: "Continue into ",
            href: "/flower",
            label: "The Flower",
            after: " for appearance, moisture, storage, and quality reading after the glands are preserved.",
          },
        ],
      },
      {
        id: "maturity-and-color",
        heading: "How Trichomes Mature",
        paragraphs: [
          "Young gland heads often appear clear. As the flower matures, many heads become cloudy or milky, and some develop amber tones. Cultivators read the proportion and distribution of these stages across representative flower sites. Pistils, swelling bracts, aroma, plant health, and the intended finished profile add context to the color view.",
          "Maturity arrives as a window rather than a single instant. Upper and lower sites receive different light and can progress at different rates. Looking across the canopy gives the grower a more complete picture. The chosen harvest moment captures one balance of gland maturity and aromatic expression for the finished flower.",
          "After harvest, gentle handling supports the surface the plant built. Temperature, light, time, and physical contact influence aromatic preservation and gland condition. A well-preserved flower lets a buyer see the living story clearly: location, gland form, resin, maturity, and careful passage into the cured harvest.",
          "Harvest timing and drying inherit the trichome story the plant built. Growers read clear-to-cloudy-to-amber patterns as one maturity cue among several, then hand the cut to controlled drying and curing so aromatic character and surface condition can settle without rough handling. A later package still shows the chosen window only if the dry room and cure jar protect what the glands already produced.",
        ],
        contextualLinks: [
          {
            before: "Follow maturity reading in ",
            href: "/plant/harvest-timing",
            label: "harvest timing",
            after: ", where trichome, pistil, and whole-plant cues define the window the resin profile inherits.",
          },
          {
            before: "See how that window is carried in ",
            href: "/plant/drying-and-curing",
            label: "drying and curing",
            after: ", where moisture movement and multi-week observation protect aromatic character and gland condition.",
          },
          {
            before: "Start from the ",
            href: "/",
            label: "Presidential Cannabis plant guide home",
            after: " anytime you need the full map of brand education beside this trichomes chapter.",
          },
        ],
      },
    ],
    externalLink: { href: "https://presidentialmoonrocks.com/find-us", label: "View licensed retailers for trichome-rich Presidential products" },
  },
  {
    path: "/plant/cannabinoids-in-the-plant",
    kind: "article",
    silo: "plant",
    h1: "Cannabinoids in the Living Plant",
    title: "Cannabinoids in the Living Plant",
    description: "What cannabinoids are in the living cannabis plant, where the plant produces them, their acidic form, and their place in flower development.",
    wordTarget: [1100, 1250],
    intro: [
      "Cannabinoids are compounds the living cannabis plant produces primarily in the resin glands concentrated on its flowers and nearby leaves. The plant predominantly biosynthesizes and accumulates them in acidic forms as the flower develops. Heat converts those compounds into other forms; for understanding the living plant, the essential picture is their origin in glandular resin and their growth alongside the flower.",
      "This location explains why flower and trichomes belong at the center of plant study. Bracts and sugar leaves create the surface, stalked resin glands rise across it, and cannabinoids accumulate inside the gland heads. Genetics sets a range for production, while cultivation, maturity, and environmental conditions influence the expression captured at harvest.",
      "Presidential Cannabis publishes this cannabinoids guide as adult 21+ botanical literacy: where the living plant produces resin compounds, why acidic forms dominate before harvest, and how genetics, environment, and maturity shape what the flower carries into the jar. The brand name here is the company and publisher. Product art and retailer paths stay on the official catalog; this page stays with glandular production, developmental timing, and plant-centered observation.",
    ],
    leadBlocks: surferLeadBlocks["/plant/cannabinoids-in-the-plant"],
    sections: [
      {
        id: "biosynthesis-in-flower",
        heading: "Production in the Flower",
        paragraphs: [
          "Cannabinoid production develops with the reproductive stage. As female flowers form, glandular trichomes become more abundant across their bracts and surrounding sugar leaves. Inside the gland heads, the plant builds a resin mixture that also contains terpenes and other compounds. The visible frost on mature flower is therefore an external sign of many microscopic production sites.",
          "Different gland forms contribute at different scales. Tiny bulbous glands occur across plant surfaces, capitate-sessile glands sit close to the surface, and capitate-stalked glands become prominent on mature flower. Their rounded heads provide a specialized space for resin. Because the largest concentration sits on the harvested flower, careful observation naturally focuses there.",
          "Acidic forms are the living plant's predominant biosynthetic starting forms. That fact belongs to botany: it describes what the plant mainly makes before harvest and processing. The named proportions vary by genetics, phenotype, flower site, maturity, and growing environment, giving each plant and batch its own developing resin profile.",
          "Reading production as anatomy keeps the story concrete. The flower supplies the gland-bearing surface; the trichome supplies the specialized head; the resin inside that head holds the developing mixture. A frosted cola is therefore many production sites working together rather than a single uniform object. Close inspection and whole-plant context both matter because canopy position and local conditions influence how densely those sites develop.",
          "This botanical frame also clarifies what frost does and does not show. Abundant glands indicate a rich glandular surface. They do not, by themselves, name the compounds or fix their proportions. Genetics, phenotype, maturity, and cultivation fill in that next layer. Keeping surface observation and biosynthetic context distinct helps adults 21+ describe flower accurately without treating sparkle as a complete chemical summary.",
          "Acidic forms also explain why heat belongs outside living-plant literacy. On the plant, resin heads hold the biosynthetic starting state; conversion into other forms is a later handling story, not the flower's default chemistry. Adults 21+ who keep that boundary clear can talk about gland location, maturity, and cultivar range without collapsing botanical observation into product processing. The practical habit is to name where resin sits, how densely glands cover bracts and sugar leaves, and which developmental window the harvest captured.",
        ],
        contextualLinks: [
          {
            before: "Study the living gland itself in ",
            href: "/plant/trichomes",
            label: "trichomes",
            after: ", where bulbous, sessile, and stalked forms, head size, and color progression are mapped on the flower surface.",
          },
          {
            before: "Map the gland-bearing surface in ",
            href: "/plant/the-flower-structure",
            label: "flower structure",
            after: ", where bracts, pistils, sugar leaves, and colas show where resin concentrates.",
          },
          {
            before: "Return to ",
            href: "/plant",
            label: "The Cannabis Plant Guide",
            after: " for the map from annual biology and flower anatomy through resin, harvest, drying, and cure.",
          },
        ],
      },
      {
        id: "genetics-environment-maturity",
        heading: "Genetics, Environment, and Maturity",
        paragraphs: [
          "Genetics define which cannabinoid pathways a plant can strongly express and the range available to that cultivar. A seed population may show variation among phenotypes, while cuttings preserve a selected genetic individual. Breeders observe resin production alongside structure, aroma, timing, and other traits when choosing plants for future lines.",
          "The growing environment shapes expression within that inherited range. Light supports the energy demands of flower development. Temperature and humidity influence the plant and the flower's surrounding microclimate. Nutrition, water, root health, and stress management support a complete cycle. Cultivation works by helping the plant express its selected genetics consistently.",
          "Maturity adds time to the picture. Gland heads develop from clear toward cloudy and amber stages as the flower advances. Cultivators read this progression across many sites, together with the whole plant, to select a harvest window. The harvest captures the cannabinoids present in the living resin at that chosen stage.",
          "That window is a decision about development, not a single universal day. Upper and lower sites can advance at different rates, and cultivars reach preferred balances on their own schedules. Connecting gland color, pistil and bract cues, aroma, and plant health turns the cut into a recorded moment in the resin story rather than an isolated calendar guess.",
          "After the cut, drying and curing decide how that captured resin arrives as finished flower. Gradual moisture loss protects structure and aromatic character; the cure equalizes remaining moisture and lets the batch settle. At a licensed counter, package dates, nose, and handling feel become the available evidence of that handoff. Keep shopping decisions inside licensed retail channels where packaging and batch details can be verified in person.",
          "At a licensed counter, that botanical frame stays useful beside the jar. Ask which harvest or package date belongs to the batch, how the producer describes resin coverage for this cut, and whether canopy position or phenotype notes accompany the delivery. Strain name points to inheritance; dates and handling describe this run. Keeping those layers separate lets adults 21+ read cannabinoid-rich flower as agricultural product rather than a single menu promise.",
        ],
        contextualLinks: [
          {
            before: "Connect maturity signals to the cut with ",
            href: "/plant/harvest-timing",
            label: "harvest timing",
            after: ", where trichome, pistil, and whole-plant cues define the window the resin profile inherits.",
          },
          {
            before: "Follow the handoff in ",
            href: "/plant/drying-and-curing",
            label: "drying and curing",
            after: ", where temperature, humidity, darkness, and observation carry living resin into stable flower.",
          },
          {
            before: "Continue into ",
            href: "/flower",
            label: "The Flower",
            after: " for appearance, aroma, density, moisture, and storage after the harvest and cure.",
          },
          {
            before: "Place production inside the annual cycle with ",
            href: "/plant/what-cannabis-is",
            label: "what cannabis is",
            after: " when germination, vegetative growth, and flowering frame when resin develops.",
          },
          {
            before: "For inheritance beside this silo, open ",
            href: "/genetics",
            label: "Genetics",
            after: " when parentage, selection, and batch variation explain why resin expression differs across cultivars.",
          },
        ],
      },
    ],
    externalLink: { href: "https://presidentialmoonrocks.com/find-us", label: "Find flower-founded Presidential formats at licensed retailers" },
  },
  {
    path: "/plant/the-flower-structure",
    kind: "article",
    silo: "plant",
    h1: "The Anatomy of a Cannabis Flower",
    title: "The Anatomy of a Cannabis Flower",
    description: "The anatomy of cannabis flower, including bracts, calyxes, pistils, sugar leaves, colas, and the surfaces that carry resin.",
    wordTarget: [1100, 1250],
    intro: [
      "A cannabis flower is a cluster of many small reproductive flowers arranged along a branch. Bracts surround the reproductive structures, pistils extend outward, sugar leaves sit among the cluster, and many flower sites can build into a cola. Resin glands cover the bracts and close leaves most densely, giving mature flower its aromatic and frosted surface.",
      "Learning the parts makes the finished piece easier to read. The rounded shapes visible on a trimmed flower come mainly from overlapping bracts. Fine hair-like pistils trace stages of development. Small leaves give the cluster additional surface and structure. The stem and branching pattern organize these parts into the larger form determined by genetics and cultivation.",
      "Presidential Cannabis publishes this flower-structure guide as adult 21+ plant literacy: plain language for bract, calyx, pistil, sugar leaf, cola, and trichome placement; how that anatomy shows up in appearance, density, harvest timing, and finished flower; and how to talk about structure at a licensed counter. No medical claims. The job is a botanical map that stays checkable beside the jar.",
    ],
    leadBlocks: surferLeadBlocks["/plant/the-flower-structure"],
    sections: [
      {
        id: "bracts-pistils-calyx",
        heading: "Bracts, Pistils, and the Calyx",
        paragraphs: [
          "The bract is the small leaf-like structure that surrounds the female flower's reproductive parts. As flowering advances, bracts swell and overlap, creating much of the mass and contour recognized as a cannabis bud. Their exposed surfaces develop abundant glandular trichomes, which is why the bract sits at the center of flower anatomy and quality observation.",
          "The calyx is the protective floral structure formed by sepals in many flowering plants. Cannabis writing often uses calyx as a casual name for the swollen bract, so the two terms commonly appear together in descriptions. A precise view keeps the bract in focus while recognizing the established vocabulary used by growers and buyers.",
          "Pistils are part of the flower's reproductive system. Their slender stigmas extend from the bract and receive pollen when reproduction occurs. They often begin pale and become orange, rust, or brown as the flower matures. Their color and posture add one maturity signal beside trichome development, bract swelling, aroma, and the condition of the whole plant.",
          "Trichomes sit most densely on those same bract faces and nearby sugar leaves. The frosted look is glandular resin concentrated where the flower built its richest surfaces, not a separate layer painted onto the bud. Structure explains why frost tracks certain contours and thins along stem or handled edges.",
          "Appearance and density inherit this architecture. Overlapping bracts create the rounded silhouette buyers recognize; how tightly those bracts pack, how much sugar leaf remains, and how the cola was shaped all change whether a piece looks open, compact, leafy, or closely trimmed.",
          "Harvest timing reads the same parts in motion. Bract swell, pistil color and posture, and trichome clarity or amber tones describe maturity on the living plant. Those cues name development on this cultivar, not a universal calendar or a medical promise.",
        ],
        contextualLinks: [
          {
            before: "The full ",
            href: "/plant/what-cannabis-is",
            label: "flowering",
            after: " cycle shows how bracts, pistils, sugar leaves, and resin glands develop into the structure seen at harvest.",
          },
          {
            before: "The Presidential Cannabis ",
            href: "/",
            label: "guide",
            after: " connects this anatomy to flower quality, genetics, choosing, and the licensed-retail path.",
          },
          {
            before: "See where resin concentrates in ",
            href: "/plant/trichomes",
            label: "trichomes",
            after: ", the glandular heads that frost bract and sugar-leaf surfaces.",
          },
          {
            before: "Follow maturity cues through ",
            href: "/plant/harvest-timing",
            label: "harvest timing",
            after: " when bract swell, pistils, and gland color are read together before the cut.",
          },
        ],
      },
      {
        id: "sugar-leaves-and-colas",
        heading: "Sugar Leaves and Colas",
        paragraphs: [
          "Sugar leaves are the small leaves that emerge from within and around the flower cluster. Their name comes from the sparkling resin glands that can make them appear dusted with sugar. They contribute surface area, photosynthesis, and structure while the flower grows. During trimming, cultivators shape how much of this close leaf remains on the finished flower.",
          "A cola is a larger grouping of flower sites concentrated along a stem, especially at a branch tip. The main cola forms at the plant's leading point, while side branches develop additional colas. Genetics, training, light distribution, branch support, and spacing influence their size and shape. A cola can later be separated into smaller pieces for drying, trimming, and packaging.",
          "All of these parts carry a cultivation record. Bract spacing reveals growth pattern, pistils show development, sugar leaves show resin near the flower, and the cola reflects canopy organization. Reading the anatomy gives density and appearance a botanical basis and shows exactly where the plant places its richest resin-bearing surfaces.",
          "Finished flower inherits that map. After dry and cure, buyers still read bract contour, pistil color, sugar-leaf trim, and how tightly sites packed along the stem. Density talk is clearer when it names those parts instead of ranking jars by feel alone.",
          "At a licensed counter, keep structure questions concrete. Ask how this batch's bract packing and trim compare with the last delivery of the same name, whether the producer favors a leafier or closer finish for this cut, and which harvest or package dates belong to the jar. Pair answers with what you see so the vocabulary stays adult retail literacy, not a medical claim.",
        ],
        contextualLinks: [
          {
            before: "Continue into ",
            href: "/flower",
            label: "The Flower",
            after: " for appearance, aroma, density, moisture, and storage after anatomy is clear.",
          },
          {
            before: "Read visible contour and frost through ",
            href: "/flower/appearance",
            label: "appearance",
            after: " when bract shape, pistils, and trim meet the eye on the shelf.",
          },
          {
            before: "Connect packing and feel in ",
            href: "/flower/density-and-structure",
            label: "density and structure",
            after: " where bract fill and cola organization explain how a piece sits in the hand.",
          },
          {
            before: "Return to ",
            href: "/plant",
            label: "The Cannabis Plant Guide",
            after: " for the map from annual biology and resin glands through harvest into post-harvest care.",
          },
        ],
      },
    ],
    externalLink: { href: "https://presidentialmoonrocks.com/find-us", label: "See Presidential flower formats at a licensed store" },
  },
  {
    path: "/plant/harvest-timing",
    kind: "article",
    silo: "plant",
    h1: "How Harvest Timing Shapes the Flower",
    title: "How Harvest Timing Shapes the Flower",
    description: "How cultivators read cannabis flower maturity and how earlier, central, and later harvest windows shape the finished flower.",
    wordTarget: [1100, 1250],
    intro: [
      "Harvest timing selects the stage of maturity that becomes finished cannabis flower. Cultivators read trichome clarity and color alongside pistils, bract development, aroma, plant condition, and the intended profile. An earlier or later choice captures a different balance of floral freshness, resin maturity, aromatic character, and physical structure.",
      "The harvest window spans a period rather than a single universal day. Genetics influences flowering length, and every garden adds its own environment. Even within one plant, upper and lower flower sites can advance at different rates. A sound decision therefore comes from representative observation across the canopy and from familiarity with the cultivar through complete cycles.",
      "Presidential Cannabis publishes this harvest-timing guide as adult 21+ plant literacy: how growers read a maturity window rather than a single calendar date, how trichome and pistil cues describe progress without guaranteeing one aromatic outcome, and how the chosen cut hands work to drying and curing. The brand name here is the company and publisher. Product art and retailer paths stay on the official catalog; this page stays with observation, windows, and post-harvest continuity.",
    ],
    leadBlocks: surferLeadBlocks["/plant/harvest-timing"],
    sections: [
      {
        id: "reading-maturity",
        heading: "How Cultivators Read Maturity",
        paragraphs: [
          "Trichome heads provide a close view. Many begin clear, move toward a cloudy or milky appearance, and develop amber tones as maturity advances. A hand lens or microscope makes this progression visible. Growers look across several flowers and several positions because a bright top site may mature ahead of a shaded lower site.",
          "The rest of the flower supplies context. Bracts swell, paired stigmas change color and position, aroma develops, and the complete inflorescence advances on a genotype-specific schedule. Each cultivar presents these signs in its own proportions. A grower's history with the same genetics makes the combined reading especially valuable.",
          "The intended finished flower also guides the decision. Cultivators may select a point that emphasizes bright aromatic definition and lively surface color, or allow additional time for fuller bract development and a greater share of amber glands. The strongest harvest choice aligns maturity, plant health, environmental conditions, and the expression the grower set out to preserve.",
          "A harvest window is a range, not a stamped appointment on the calendar. Flowering-length estimates give orientation, yet genotype, light history, canopy position, and plant condition move the actual days. Growers therefore treat predicted weeks as a planning frame and treat daily observation as the decision tool. Clear, cloudy, and amber trichome language names what a lens shows; it does not promise a single finished aroma or density for every cultivar cut on the same day.",
          "Pistils, bract swell, and whole-plant vigor supply the same kind of descriptive vocabulary. Color change on stigmas and fuller bract mass can track advancing maturity, while a plant under stress may present mixed signals that ask for caution rather than a forced cut. Reading several sites—top, mid, and lower—keeps one bright cola from speaking for the entire canopy. That habit matters because finished flower will later be judged as a batch, and the batch inherits whatever stage the grower chose across those positions.",
        ],
        contextualLinks: [
          {
            before: "Return to ",
            href: "/plant",
            label: "The Cannabis Plant Guide",
            after: " for the map from annual biology and resin glands through harvest into post-harvest care.",
          },
          {
            before: "Review the anatomy behind these cues in ",
            href: "/plant/the-flower-structure",
            label: "the flower structure",
            after: ", where bracts, pistils, and clustered sites explain what maturity reading is looking at.",
          },
          {
            before: "Revisit ",
            href: "/plant/what-cannabis-is",
            label: "what cannabis is",
            after: " when you want the annual cycle and resin purpose that make a harvest window meaningful.",
          },
        ],
      },
      {
        id: "finished-expression",
        heading: "Earlier and Later Expressions",
        paragraphs: [
          "An earlier harvest within a cultivar's accepted window may present a greater share of clear-to-cloudy glands, lighter stigma tones, and bracts that are still developing. Chemistry and aroma follow genotype-specific patterns, so these visual signals describe maturity rather than promising one universal aromatic or cannabinoid result.",
          "A later point may carry more amber glands, advanced stigma color, and additional bract development. Trichomes mature asynchronously and cultivars reach different chemical peaks at different times. These are observational inputs rather than a universal clock; the intended profile, plant history, representative sampling, and complete flower guide the decision together.",
          "Drying and curing determine how the harvest decision reaches the finished flower. Controlled moisture loss stabilizes structure, while curing allows remaining moisture and the aromatic profile to continue changing under observation. Common industry practice often spans several weeks. Timing captures the moment, and post-harvest care carries its changing signature toward the package.",
          "Two harvests of the same cut can still differ. Garden climate, feeding finish, canopy density, and exact day within the window shift water content, aromatic intensity, and how tightly bracts have filled. The cultivar name identifies the genetics; harvest and batch labels identify this run. At a licensed counter, ask when the flower was cut, how it was dried and cured, and whether those dates sit separate from the strain title—so one name never stands in for timing evidence.",
          "Timing also sets the starting state that drying and curing must carry. An earlier-window cut may arrive with a brighter aromatic edge and bracts still settling; a later-window cut may arrive denser and further along in gland color. Neither description doses or ranks quality by itself. What matters is continuity: the dry room and cure jar preserve the chosen maturity rather than rewriting it. Asking how a producer coordinated the cut with hang conditions connects the living-plant decision to the texture and aroma in the sealed package.",
        ],
        contextualLinks: [
          {
            before: "Follow the handoff in ",
            href: "/plant/drying-and-curing",
            label: "drying and curing",
            after: ", where moisture movement and multi-week observation carry the chosen window into stable flower.",
          },
          {
            before: "Continue into ",
            href: "/flower",
            label: "The Flower",
            after: " for appearance, aroma, moisture, and storage after the harvest decision is finished.",
          },
          {
            before: "Start from the ",
            href: "/",
            label: "Presidential Cannabis plant guide home",
            after: " anytime you need the full map of brand education beside this harvest chapter.",
          },
        ],
      },
    ],
    externalLink: { href: "https://presidentialmoonrocks.com/find-us", label: "Locate recent Presidential batches through licensed shops" },
  },
  {
    path: "/plant/drying-and-curing",
    kind: "article",
    silo: "plant",
    h1: "Drying and Curing",
    title: "Drying and Curing Cannabis",
    description: "What drying and curing do for raw cannabis flower, how long the stages take, and how they preserve aroma, moisture, structure, and quality.",
    wordTarget: [1100, 1250],
    intro: [
      "Drying gradually removes moisture from harvested cannabis, and curing allows the remaining moisture to settle more evenly while aroma and texture continue changing. Together, the stages turn fresh plant material into stable finished flower. Common industry practice often spans several weeks, with the exact duration guided by flower size, structure, producer method, temperature, humidity, darkness, air movement, and observation.",
      "Post-harvest care matters because flower remains physically and aromatically active after cutting. Water moves from the interior toward the surface. Terpenes respond to heat, light, air, and time. Bracts and leaves change texture as they lose moisture. A deliberate process guides these changes at a steady pace and creates a balanced result that holds its character in the package.",
      "Presidential Cannabis publishes this drying and curing guide as adult 21+ post-harvest literacy: how temperature, humidity, darkness, and air movement carry a harvest decision into stable finished flower. The brand name here is the company and publisher. Product art and retailer paths stay on the official catalog; this page stays with moisture movement, aromatic preservation, and the multi-week handoff from fresh cut to sealed package.",
    ],
    leadBlocks: surferLeadBlocks["/plant/drying-and-curing"],
    sections: [
      {
        id: "the-dry",
        heading: "What Happens During Drying",
        paragraphs: [
          "Freshly harvested cannabis contains substantial water in its stems, leaves, and flowers. Drying begins in a dark, climate-controlled space with gentle air exchange around the hanging plant or separated branches. The environment encourages moisture to leave gradually from throughout the flower rather than racing from the outer surface.",
          "A steady dry supports shape and aromatic preservation. The flower's exterior becomes settled while the interior continues releasing moisture. Smaller stems gain a firmer snap and the flower reaches a texture suited to trimming and containers. Cultivators use time, touch, stem behavior, room readings, and experience with the cultivar to judge the transition.",
          "Terpenes are volatile and can change during drying, curing and storage. Lower temperatures, darkness and a measured pace help preserve the aromatic fraction. Air movement during postharvest handling keeps the room consistent around the flowers, while thoughtful spacing gives each branch access to the same general conditions.",
          "Room design turns those principles into daily practice. Stable temperature and humidity keep moisture leaving at a predictable rate; darkness limits light stress on volatile compounds; gentle circulation prevents stagnant pockets without blasting the surface dry. Crowded racks create uneven zones, while generous spacing lets each branch share the same general climate. Growers adjust hang method, branch size, and trim timing to the cultivar's density so the dry remains gradual rather than forced.",
          "The dry also inherits the harvest window. Flower cut earlier or later within a cultivar's accepted range arrives with different water content, bract development, and aromatic intensity. That starting state shapes how long the room needs and how the piece will feel when stems begin to firm. Reading the dry as the next chapter of timing—not a separate ritual—keeps the living-plant story continuous from canopy observation through the first sealed container.",
          "Resin surfaces need the same patience. Stalked trichome heads sit exposed on bracts and sugar leaves, so rough handling, high heat, or harsh airflow can scuff glands before the flower ever reaches a jar. A measured hang keeps branches supported, limits unnecessary contact, and lets moisture leave without stripping the aromatic film the plant built. That care is why frost that looked intact at cut still reads intact after the dry.",
          "Hang method and trim timing also follow architecture. Whole-plant or large-branch hangs slow the outer surface on dense colas; earlier branch separation can help open forms breathe more evenly. Wet-trim versus dry-trim is a producer choice matched to cultivar packing, room capacity, and labor—not a universal ranking. Naming bract spacing and cola shape before the cut makes those choices easier to defend across runs.",
        ],
        contextualLinks: [
          {
            before: "Connect the cut to this stage with ",
            href: "/plant/harvest-timing",
            label: "harvest timing",
            after: ", where trichome, pistil, and whole-plant cues define the window the dry must preserve.",
          },
          {
            before: "Protect the glandular surface by revisiting ",
            href: "/plant/trichomes",
            label: "trichomes",
            after: " when coverage, head condition, and careful handling explain what the dry room must not erase.",
          },
          {
            before: "Map bracts, pistils, and cola packing in ",
            href: "/plant/the-flower-structure",
            label: "the flower structure",
            after: " so hang method and trim timing match the architecture arriving from the canopy.",
          },
          {
            before: "Return to ",
            href: "/plant",
            label: "The Cannabis Plant Guide",
            after: " for the map from annual biology and resin glands through harvest into post-harvest care.",
          },
        ],
      },
      {
        id: "the-cure",
        heading: "What Curing Adds",
        paragraphs: [
          "Curing begins when dried flower moves into sealed containers. Moisture remaining near the center redistributes through the piece, bringing the surface and interior toward balance. Containers are opened and observed on a schedule suited to the flower and its readings. Over time, texture becomes more even and the aroma presents as a unified profile.",
          "The cure also creates a stable point for evaluation. A well-cured piece feels settled on the outside and gently resilient within. Bracts separate cleanly with handling, and the flower retains its structure. Aroma opens with definition rather than carrying the fresh green character of a newly cut plant.",
          "Several weeks gives the process room to work. The exact timeline follows flower size, density, starting moisture, room conditions, and the grower's method. Consistency is the common value: gradual drying prepares the flower, controlled curing balances it, and cool, dark storage preserves that balance. The cure therefore decides how faithfully cultivation and harvest arrive in the finished package.",
          "Structure and density shape how the cure behaves. Compact pieces and open pieces release and equalize moisture on different schedules, so batch grouping and observation protect both forms without forcing one texture onto every cultivar. When adults later evaluate finished flower, bract spacing, silhouette, and gentle resilience are easier to read because the cure respected the inherited architecture instead of racing past it.",
          "After cure, the same literacy that began with the living plant still applies. Annual cycle and resin purpose explain why the flower carries aromatic and glandular detail into the jar; inheritance language explains why two cultivars need different hang and jar timelines. At a licensed counter, package dates, nose, and handling feel become the available evidence of that work. Keep shopping decisions inside licensed retail channels where packaging and batch details can be verified in person.",
          "Moisture literacy after the jar is sealed stays observational. Adults 21+ can note whether the surface feels settled rather than brittle or spongy, whether aroma opens with definition on first crack, and whether package dates sit close enough to support that read. Those cues describe the cure's outcome without inventing dosing advice; they also connect cleanly to how moisture and storage habits protect the same balance once the container leaves the counter.",
        ],
        contextualLinks: [
          {
            before: "Read ",
            href: "/flower/density-and-structure",
            label: "density and structure",
            after: " for how compact and open forms influence handling, drying pace, and cured feel.",
          },
          {
            before: "Carry the jar forward with ",
            href: "/flower/moisture-and-cure",
            label: "moisture and cure",
            after: " when texture, aroma definition, and freshness cues describe how the finished batch presents.",
          },
          {
            before: "Protect that balance after purchase through ",
            href: "/flower/storing-flower",
            label: "storing flower",
            after: ", where cool, dark, and sealed habits continue the same preservation logic.",
          },
          {
            before: "Continue into ",
            href: "/flower",
            label: "The Flower",
            after: " for appearance, aroma, moisture, and storage after the cure is complete.",
          },
          {
            before: "Revisit ",
            href: "/plant/what-cannabis-is",
            label: "what cannabis is",
            after: " when you want the annual cycle and resin purpose behind post-harvest care.",
          },
          {
            before: "For inheritance context beside this silo, open ",
            href: "/genetics",
            label: "Genetics",
            after: " when parentage and selection explain why cultivars need different hang and jar timelines.",
          },
        ],
      },
    ],
    externalLink: { href: "https://presidentialmoonrocks.com/find-us", label: "Discover carefully finished Presidential products near you" },
  },
];
